modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="elementary_craft"
version="1.0.0"
displayName="Elementary Craft"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Tom, MCreator"

[[dependencies.elementary_craft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




